name: Sync Fork and Trigger Build

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SECRET }}

      - name: Merge Upstream and Check for Changes
        id: sync
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          BEFORE_SHA=$(git rev-parse HEAD)
          git remote add upstream https://github.com/optiscaler/OptiScaler.git
          git fetch upstream
          git merge upstream/master || exit 0
          AFTER_SHA=$(git rev-parse HEAD)
          echo "changes_detected=$([ \"$BEFORE_SHA\" != \"$AFTER_SHA\" ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Push Changes
        if: steps.sync.outputs.changes_detected == 'true'
        run: git push origin master

      - name: Dispatch Build Event
        if: steps.sync.outputs.changes_detected == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SECRET }}
          event-type: sync-upstream
          client-payload: |
            {
              "ref": "refs/heads/master",
              "sha": "${{ steps.sync.outputs.changes_detected }}"
            }
