# GitHub Action for syncing a fork with its upstream repository by merging
name: Sync Fork (Merge)

on:
  schedule:
    # 每四小时执行一次
    - cron: '0 */4 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          # 我们需要完整的历史记录来正确合并
          fetch-depth: 0
          # 仍然需要 PAT 来获得推送权限
          token: ${{ secrets.OPTI }}

      - name: Merge Upstream Branch
        run: |
          # 1. 配置 Git 用户信息，这样才能创建合并提交
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # 2. 添加上游（原始）仓库的远程地址
          # !!!【请修改这里】!!! 将 URL 替换为真正的上游仓库地址
          git remote add upstream https://github.com/optiscaler/OptiScaler.git

          # 3. 从上游仓库拉取最新的代码
          git fetch upstream

          # 4. 合并上游仓库的 main 分支到你自己的 main 分支
          # !!!【请修改这里】!!! 如果分支不是 main，请修改为 master 或其他
          git merge upstream/master

          # 5. 将合并后的结果推送到你的 fork 仓库
          git push origin master
        env:
          # 将你的 PAT 传递给 Git
          GH_TOKEN: ${{ secrets.OPTI }}
